CREATE OR REPLACE PROCEDURE RegistrarUsuario (pNombre in VARCHAR2,pApellido IN  VARCHAR2, pCorreo IN VARCHAR2, pTelefono IN  VARCHAR2, pContrasenna IN  VARCHAR2)
as BEGIN

INSERT INTO USERS(NAME, LAST_NAME, EMAIL, PHONE, ROL, PASSWORD, STATUS)
VALUES (pNombre, pApellido, pCorreo, pTelefono,1, pContrasenna,1);

END;

CREATE OR REPLACE PROCEDURE RegistrarFormulario (pID_USER_SOLICITUD in NUMBER, pFULLNAME IN  VARCHAR2, pEMAIL IN VARCHAR2, pPHONE IN  VARCHAR2, pSERVICIO in VARCHAR2, pMENSAJE in VARCHAR2)
as BEGIN

INSERT INTO SOLICITUD(ID_USER_SOLICITUD, FULLNAME, EMAIL, PHONE, SERVICIO, MENSAJE)
VALUES (pID_USER_SOLICITUD, pFULLNAME, pEMAIL, pPHONE, pSERVICIO, pMENSAJE);

END;


create or replace PROCEDURE ValidarSesion (
  pCorreo IN VARCHAR2,
  pContrasenna IN VARCHAR2,
  p_cursor OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM USERS 
                        WHERE EMAIL = pCorreo
                        AND PASSWORD = pContrasenna;
    END ValidarSesion;
/





